### ISSUE TITLE
[Question] How should this be setup?

### ISSUE THREAD

**Issue by shreeve** [alin23/next-coffeescript#1]
This looks very helpful! However, I can't get it running.

I've got the following `package.json` file:

```json
{
  "name": "tiny",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "coffeescript": "^2.2.2",
    "next": "^5.0.0",
    "next-coffeescript": "^1.0.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}
```
Here's my directory structure:

```
├── [ 128]  pages/
│   ├── [  49]  hello.coffee
│   └── [  53]  index.js
├── [ 108]  next.config.js
├── [186K]  package-lock.json
└── [ 454]  package.json
```

Here is `pages/index.js`:

```js
export default () => <div>Welcome to next.js!</div>
```

Here is `pages/hello.coffee`:

```coffee
export default => <div>Word to your mother</div>
```

I also have this `next.config.js` file:

```js
// next.config.js
const withCoffeescript = require('next-coffeescript')
module.exports = withCoffeescript()
```

Do I need to add some `babel` packages for supporting JSX within `coffeescript` or make some other changes?

**Comment by alin23** [comment]
Seems like for the moment, only the canary version of Next.js supports pages with different extensions.
So if you want to use this module, do: `yarn add next@canary`

Thanks for opening an issue for this, I added a notice in the README about it.

Also, `index.js` can be changed to `index.coffee`. The only file that's required to be `.js` is the `next.config.js`
