### ISSUE TITLE
Help on simple next-coffeescript Project

### ISSUE THREAD

**Issue by jimmychu0807** [alin23/next-coffeescript#3]
Hi, 

I create the simplest next project, with the following `pages/index.coffee` and `next.config.js`

index.coffee

```
import React from 'react'

export default class Index extends React.Component
  render: ->
    <div>
      <p>Hello World</p>
    </div>
```

next.config.js

```
const withCoffeescript = require('next-coffeescript')
module.exports = withCoffeescript({
  webpack(config, options) {
    return config
  },
  coffeescriptLoaderOptions: {
    literate: true
  }
})
```

Visiting `localhost:3000` says `{ Error: The default export is not a React Component in page: "/"`

What's wrong with my config? Thanks.

**Comment by alin23** [comment]
Hi @jimmychu0807 

Your `index.coffee` file is not a Literate CoffeeScript file. And I don't think it should be. Just remove the `literate: true` option from `coffeescriptLoaderOptions` and it should work.

**Comment by jimmychu0807** [comment]
Indeed. Thanks for your help!

**Comment by alin23** [comment]
You welcome! ^_^
